[package]
name = "eosc-rs"
version = "0.1.0"
edition = "2024"
authors = ["Zax71"]
description = "A wrapper for EOS v2 OSC commands"
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
rosc = "~0.10"
