[package]
name = "eosc-rs"
version = "2.0.1"
edition = "2024"
authors = ["Zax71"]
description = "A wrapper for EOS v2 OSC commands"
repository = "https://github.com/zax71/eosc-rs"
readme = "README.md"
license = "MIT"

[dependencies]
rosc = "~0.10"
snafu = "0.8.9"
